require 'acts-as-taggable-on'

require 'social_engine/engine'

require 'social_engine/authenticated_system'
require 'social_engine/localized_application'  
require 'social_engine/social_engine_sha1_crypto_method'    
require 'social_engine/i18n_extensions'  
require 'social_engine/viewable'    
require 'social_engine/url_upload'  
require 'social_engine/engines_extensions'  

require 'configatron'
require 'hpricot'
require 'htmlentities'
require 'haml'
require 'sass-rails'
require 'aws/s3'
require 'ri_cal'
require 'rakismet'
require 'kaminari'
require 'dynamic_form'
require 'friendly_id'
require 'paperclip'
require 'acts_as_commentable'
require 'recaptcha/rails'
require 'omniauth'
require 'authlogic'
require 'prototype-rails'
require 'rails_autolink'
require 'meta_search'
require 'tinymce-rails'
require 'sanitize'


include EnginesExtensions